### ISSUE TITLE
Use the Insiders config directory when running VS Code Insiders

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#52]
I just setup a new machine and I hit this:

```
ENOENT: no such file or directory, open '/home/daniel/.config/Code/User/gpm-recentItems.json': Error: ENOENT: no such file or directory, open '/home/daniel/.config/Code/User/gpm-recentItems.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at RecentItems.saveToFile (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.3.1/src/recentItems.js:34:12)
    at RecentItems.addProject (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.3.1/src/recentItems.js:51:14)
    at GitProjectManager.openProject (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.3.1/src/gitProjectManager.js:249:25)
    at onResolve (/home/daniel/.vscode-insiders/extensions/felipecaputo.git-project-manager-1.3.1/src/gitProjectManager.js:160:22)
    at Object.m [as _notify] (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:63456)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:67030)
    at n.Class.derive._oncancel._run (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:68858)
    at n.Class.derive._oncancel._completed (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:68299)
    at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:75260
    at n.Class.derive._creator.done (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:70159)
    at Object.m [as _notify] (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:63598)
    at Object.enter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:67030)
    at n.Class.derive._oncancel._run (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:68858)
```

**Comment by Tyriar** [comment]
This is actually caused because you should be checked for and creating `~/.config/Code - Insiders/...` if you're on Insiders.
