### ISSUE TITLE
Support for VS Code portable mode

### ISSUE THREAD

**Issue by jrehwaldt** [felipecaputo/git-project-manager#81]
[VS Code added support for portable mode](https://code.visualstudio.com/docs/editor/portable) when the directory `data` is available alongside the binary on zip-versions.

This behavior is [not yet supported by this project manager](https://github.com/felipecaputo/git-project-manager/blob/master/src/gitProjectManager.js#L25-L26) and manifests as follows:

```
Error: ENOENT: no such file or directory, open 'C:\Users\joopkaup\AppData\Roaming\Code - Insiders\User\gpm-recentItems.json'
	at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
	at Object.fs.writeFileSync (fs.js:1303:33)
	at RecentItems.saveToFile (D:\config\.code-extensions\felipecaputo.git-project-manager-1.6.1\src\recentItems.js:34:12)
        at ...
```

[This open PR](https://github.com/alefragnani/vscode-project-manager/pull/204/files) fixes the exact same problem in another comparable plugin.

**Comment by felipecaputo** [comment]
Sorry for taking too long, I'm just fixing some errors with my latests PR and will take a look at this really soon

**Comment by felipecaputo** [comment]
Hi @jrehwaldt can you please validate if the MR #79 that was release on 1.7.0 fix this issue?

**Comment by jrehwaldt** [comment]
The issue still persists, because MR #79 fixes an unrelated issue related to the name of the product. This issue is about the location of the config.

**Comment by felipecaputo** [comment]
Thanks for the quick reply, I'll look into this today

And release it on 1.7.1
